version: 1.1.1-CI-{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - master
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install: 
  - echo y | "C:\Program Files (x86)\Android\android-sdk\tools\android.bat" update sdk -u -a -t tools
  - echo y | "C:\Program Files (x86)\Android\android-sdk\tools\android.bat" update sdk -u -a -t platform-tools
  - echo y | "C:\Program Files (x86)\Android\android-sdk\tools\android.bat" update sdk -u -a -t build-tools-26.0.2
  - echo y | "C:\Program Files (x86)\Android\android-sdk\tools\android.bat" update sdk -u -a -t android-26
  - echo y | "C:\Program Files (x86)\Android\android-sdk\tools\android.bat" update sdk -u -a -t android-15
before_build:
  # Restore each project instead of all solution
  - ps: >- 
        nuget restore .\src\Askmethat.XForms.Controls.Forms\Askmethat.XForms.Controls.Forms.csproj -PackagesDirectory ..\packages
        
        nuget restore .\src\Askmethat.XForms.Controls.iOS\Askmethat.XForms.Controls.iOS.csproj -PackagesDirectory ..\packages
        
        nuget restore .\src\Askmethat.XForms.Controls.Android\Askmethat.XForms.Controls.Android.csproj -PackagesDirectory ..\packages
init:
  # Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      else
      {
        Update-AppveyorBuild -Version "$env:version"
      }
build:
  project: src\Askmethat.XForms.Controls.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
after_build:
  - ps: >-
      msbuild .\src\Askmethat.XForms.Controls.NuGet\Askmethat.XForms.Controls.NuGet.nuproj /t:Build /p:Platform=AnyCPU /p:Configuration=Release /p:Version=$env:APPVEYOR_BUILD_VERSION
artifacts:
  - path: src\Askmethat.XForms.Controls.NuGet\bin\Release\*.nupkg
    name: NuGet
environment:
  nuget_key:
    secure: DDi8FfYEKjULby1vJKBDELwBExLHnsmTl5C1YADPpQVaoQaEYgVlwRaQiOOiGu8E
deploy:
  - provider: NuGet
    api_key:
      secure: DDi8FfYEKjULby1vJKBDELwBExLHnsmTl5C1YADPpQVaoQaEYgVlwRaQiOOiGu8E
    on:
      appveyor_repo_tag: true
